### ISSUE TITLE
Link to code pointer in tutorials/kvscheduler point to plugins/kvscheduler

### ISSUE THREAD

**Issue by chrismetz09** [ligato/docs#19]
instead of https://github.com/ligato/vpp-agent/tree/master/examples/tutorials/05_kv-scheduler

**Comment by ondrej-fabry** [comment]
Not sure what you meant here, since the reason why [Tutorials/KVScheduler](https://docs.ligato.io/en/latest/tutorials/05_kv-scheduler/) links to https://github.com/ligato/vpp-agent/tree/master/examples/tutorials/05_kv-scheduler is that it contains full source code relevant to that tutorial.

However I do agree that some linking between tutorials/plugins/guides should be added just like I mentioned in #17

**Comment by chrismetz09** [comment]
apologies - meant next paragraph beginning with "This tutorial shows how to use the .."
